### PR TITLE
Added Share Command

### PR DESCRIPTION
**Pull request by boredom101**
The share command allows you to keep track of files on pastebin with metadata.

The process is simple:

1. Run `share put <type> <filename>` as many times as you want
2. Run `share get <filename>` for any of the files
3. The file will be in its previous position

### CODE REVIEW

**Comment by Rami-Sabbagh** [comment]
I didn't really understand, How is this different than the `pastebin` command ? Why does it use the config utils ?

**Comment by boredom101** [comment]
It chains the pastes, by placing the previous code in the file, allowing you to get by filename, while saving only one code to config.

**Comment by Rami-Sabbagh** [comment]
Well, why not make this an optional program ? I usually write a simple script which installs my program and upload it into pastebin, so people only have to type 'pastebin run <code>' to install my program.

**Comment by boredom101** [comment]
Alright, sorry, should this pull request be closed?

**Comment by Rami-Sabbagh** [comment]
You don't have to be sorry, but there're some things that the developer doesn't want in the official build or like that

**Pull request closed without merging**
