### PR TITLE
Implement snap packaging, snaps are universal linux packages

### PR DESCRIPTION
**Pull request by brlin-tw**
**Type:**
Improvement

**Description:**
This patch implements the necessary details to package LIKO-12 as a snap
that can be installed on a wide range of GNU/Linux distributions with
ease.

### CODE REVIEW

**Comment by Rami-Sabbagh** [comment]
Very nice work dude !
That's very nice, you saved me the effort required for the most of the work.

But there are still multiple issues:
- Could you make it install/bundle lua-sec in the process ?
- LIKO-12 has continues integration implemented through Travis,
and the new snap files should be added the the blacklist at:
The `Removing unnecessary files...` section of https://github.com/LIKO-12/LIKO-12/blob/master/Travis/before_deploy.sh#L13
- LIKO-12 does also have the ability to self build itself,
and the new snap files should be also blacklisted at https://github.com/LIKO-12/LIKO-12/blob/master/BIOS/post.lua#L86

**Comment by brlin-tw** [comment]
> Could you make it install/bundle lua-sec in the process ?

lua-sec is [already bundled](https://github.com/LIKO-12/LIKO-12/blob/53b0cdf81a9fa6183ba1333b580a3bc9ca05c48f/snap/snapcraft.yaml#L41-L45) in the snap and [should work by default](https://github.com/LIKO-12/LIKO-12/blob/53b0cdf81a9fa6183ba1333b580a3bc9ca05c48f/snap/snapcraft.yaml#L121-L127).

Do note me if it isn't, though, maybe it's a "works on my machine(TM)" situation.

**Comment by brlin-tw** [comment]
I've applied the requested changes, please review.

**Review by Rami-Sabbagh — APPROVED** [review]
It looks good, thanks for your help :)

**Comment by Rami-Sabbagh** [comment]
I want to ask, would you like to maintain the snap builds of LIKO-12 ?, you have way much more experience than me about the snaps

**Comment by brlin-tw** [comment]
Sure thing!

**Pull request merged**
