### PR TITLE
Add command to quit.

### PR DESCRIPTION
**Pull request by technomancy**
This tracks unsaved changes and asks the user to confirm quitting if they have unsaved changes.

Also fixes the case sensitivity problem.

### CODE REVIEW

**Comment by Rami-Sabbagh** [comment]
I wanted to add this, but no more lines left for help command info, must make it to request a key for showing the other page of help

**Comment by Rami-Sabbagh** [comment]
interesting saving notice, I'll add that soon™

**Comment by technomancy** [comment]
Well, could just delete the line from the help text; most people can probably guess that the way to quit is to type "quit". =)

**Comment by technomancy** [comment]
I can rebase this branch to avoid conflicts with the latest master if you want me to. Just let me know if I should remove it from the help for now.

**Comment by Rami-Sabbagh** [comment]
I'll replace help command to have a page arg

**Comment by Rami-Sabbagh** [comment]
Added shutdown command aithout saving notice (well yeah, I should make it auto save to backup.lk12 before shutting down...)

**Pull request closed without merging**
