### PR TITLE
Document HDD

### PR DESCRIPTION
**Pull request by mattx433**
Add HDD documentation. Sadly, load is documented in not the best way and drives isn't documented at all.

### CODE REVIEW

**Review by Rami-Sabbagh — CHANGES_REQUESTED** [review]
Please add
```
**Important: This function is only available in the operating system programs!**
```

**Comment by LoganDark** [comment]
@RamiLego4Game Can't you accept the PR and then make that change yourself?

**Comment by Rami-Sabbagh** [comment]
@LoganDark I'm too lazy...

**Comment by LoganDark** [comment]
:P

**Review by Rami-Sabbagh — APPROVED** [review]

**Pull request merged**
