### PR TITLE
Map editor

### PR DESCRIPTION
**Pull request by technomancy**
It's basic, but it works.

Also added `map` to the API so that users can draw them from their game.

### CODE REVIEW

**Comment by technomancy** [comment]
I rebased this on the latest master mostly so my kids could use it, but if you want to merge it that would be cool too. If you want me to make some changes just let me know.

**Comment by Rami-Sabbagh** [comment]
I want to recode it for better usage ingames, I'll properly use a Image for saveing the map

**Comment by technomancy** [comment]
Hm... I chose to store it as numbers because that's what pico 8 does, but I think there are pretty good reasons for it. Imagine if you are writing collision detection, if the map is an image, you cannot use it to see where the walls are, but if it is numbers you can say that sprites 12-18 are walls and look up a position in the map to see if moving there is allowed or not.

**Comment by Rami-Sabbagh** [comment]
I'll use the imagedata as a saving format, but it will be extracted to tables whenloading (so you can do map[x][y] == 15 or set that to the spr num you want

**Comment by technomancy** [comment]
It's easy to go one direction (number in memory->image on disk) but if you save as an image, going back to the number when you load would require scanning every pixel of the whole sprite sheet, and it would still have false positives where it could match a sprite even though it shouldn't.

For instance, if you have two sprites that look identical but should have different properties; imagine that sprite 11 is a wall and should be considered solid for collision detection logic because it's <20, but imagine you have sprite 29 that looks identical but should not be considered solid, so you can build secret doors in walls. If you save as an image and then scan the whole spritesheet to determine the numbers, all your secret doors will be converted into regular walls.

Why not just save the number to begin with?

**Pull request closed without merging**
