### PR TITLE
Store the command and navigate in them using UP key.

### PR DESCRIPTION
**Pull request by feserr**
I have implemented the UP key behaviour like the one of the SO terminals.

Now you can use previous command and you do not your time typing again the same command.

### CODE REVIEW

**Comment by feserr** [comment]
It stores empty string, for example if you press return without typing anything. I am working in a solution. If you accept the merge I will update it.

**Comment by feserr** [comment]
I fix the wrong behaviour and add the use of TAB key to autocomplete files and folder.
I also change the way you load files, now you have to type the extension to like every SO terminal, but this is not a problem because you can use TAB to autocomplete.

**Comment by Rami-Sabbagh** [comment]
sorry, I was about to merge it, but you have to fix the .liko12 thing..

**Comment by feserr** [comment]
I have fix it to work like you want, but think about typing the extension, there will be people like would want to put the extension name that they want.

**Comment by Rami-Sabbagh** [comment]
Enjoy !

**Pull request merged**
