### PR TITLE
A new terminal: xshell

### PR DESCRIPTION
**Pull request by boredom101**
A new shell that allows you to chain commands. For example the following in xshell:

`cd example & ls`

Will try to change directory to 'example' and only list the contents if successful.
You can either enter xshell interactively by just typing `xshell`, or you could just enter `xshell` followed by the command you want to do.

### CODE REVIEW

**Comment by LoganDark** [comment]
If you're going to implement chaining, why don't you go the whole mile and implement POSIX syntax?

**Comment by boredom101** [comment]
I'm thinking that I'll add the features one at a time.

**Comment by LoganDark** [comment]
I bet there's already [a POSIX parser implemented in Lua](https://github.com/jirutka/sh-parser) you can use to parse it. Then executing the commands and other logic is all that needs to be done.

**Comment by boredom101** [comment]
I found [https://github.com/jirutka/sh-parser](https://github.com/jirutka/sh-parser), I think I'll look into it.

**Comment by LoganDark** [comment]
Heh, I guess you didn't see my edit then. But have fun.

**Comment by boredom101** [comment]
Oh, didn't notice sorry. Thank you.

**Comment by LoganDark** [comment]
You're welcome

**Review by Rami-Sabbagh — CHANGES_REQUESTED** [review]
In terminal.lua
```lua
ok = term.executeFile()
```
Should be changed to
```lua
local ok = term.executeFile()
```
Otherwise it will create a global variable...

**Comment by boredom101** [comment]
I have made the change. Sorry.

**Pull request merged**
